In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_excel("/content/drive/MyDrive/bda/bda_머신러닝스터디/airbnb_preprocessed.xlsx")
df

,log_price,property_type,room_type,bathrooms,bedrooms,beds,bed_type,amenities,amenities_count,accommodates,cancellation_policy,cleaning_fee,city,latitude,longitude,number_of_reviews,review_scores_rating
0,5.010635,Apartment,Entire home/apt,1.0,1,1,Real Bed,"{""Wireless Internet"",""Air conditioning"",Kitche...",8,3,strict,True,NYC,40.696524,-73.991617,2,100
1,5.129899,Apartment,Entire home/apt,1.0,3,3,Real Bed,"{""Wireless Internet"",""Air conditioning"",Kitche...",14,7,strict,True,NYC,40.766115,-73.989040,6,93
2,4.976734,Apartment,Entire home/apt,1.0,1,3,Real Bed,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",18,5,moderate,True,NYC,40.808110,-73.943756,10,92
3,4.744932,Apartment,Entire home/apt,1.0,0,1,Real Bed,"{TV,Internet,""Wireless Internet"",""Air conditio...",12,2,moderate,True,DC,38.925627,-77.034596,4,40
4,4.442651,Apartment,Private room,1.0,1,1,Real Bed,"{TV,""Wireless Internet"",Heating,""Smoke detecto...",10,2,strict,True,SF,37.753164,-122.429526,3,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55523,5.135798,Apartment,Entire home/apt,1.0,1,1,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",24,2,moderate,True,SF,37.789989,-122.407384,24,98
55524,4.356709,Apartment,Entire home/apt,1.0,1,1,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",26,2,strict,True,Chicago,41.909067,-87.623046,6,100
55525,4.248495,House,Private room,1.0,1,1,Real Bed,"{TV,Internet,""Wireless Internet"",""Air conditio...",13,2,moderate,True,LA,34.092640,-118.343921,36,91
55526,5.043425,Apartment,Entire home/apt,2.0,2,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",15,4,moderate,True,LA,33.871549,-118.396053,16,93
55527,5.220356,Apartment,Entire home/apt,1.0,2,2,Real Bed,"{TV,Internet,""Wireless Internet"",""Air conditio...",31,5,moderate,True,NYC,40.706749,-73.942377,43,94

In [ ]:
# 빈 칼럼 만들기
df['pool'] = ''
df['breakfast'] = ''
df['internet'] = ''
df['kitchen'] = ''
df['free parking on premises'] = ''
df['air-conditioning or heating'] = ''
df['hot tub'] = ''
df['washer'] = ''
df['dryer'] = ''
df['self check-in'] = ''
df['tv'] = ''

In [ ]:
df['pool'] = df['amenities'].apply(lambda x: 1 if "Pool" in x else 0)
df['breakfast'] = df['amenities'].apply(lambda x: 1 if "Breakfast" in x else 0)
df['internet'] = df['amenities'].apply(lambda x: 1 if "Internet" or "Wireless Internet" or "Pocket wifi" in x else 0)
df['kitchen'] = df['amenities'].apply(lambda x: 1 if "Kitchen" in x else 0)
df['free parking on premises'] = df['amenities'].apply(lambda x: 1 if "Free parking on premises" in x else 0)
df['air-conditioning or heating'] = df['amenities'].apply(lambda x: 1 if "Air conditioning" or "Heating" in x else 0)
df['hot tub'] = df['amenities'].apply(lambda x: 1 if "Hot tub" in x else 0)
df['washer'] = df['amenities'].apply(lambda x: 1 if "Washer" in x else 0)
df['dryer'] = df['amenities'].apply(lambda x: 1 if "Dryer" in x else 0)
df['self check-in'] = df['amenities'].apply(lambda x: 1 if "Self Check-In" in x else 0)
df['tv'] = df['amenities'].apply(lambda x: 1 if "TV" or "Cable TV" in x else 0)

In [ ]:
df

,log_price,property_type,room_type,bathrooms,bedrooms,beds,bed_type,amenities,amenities_count,accommodates,...,breakfast,internet,kitchen,free parking on premises,air-conditioning or heating,hot tub,washer,dryer,self check-in,tv
0,5.010635,Apartment,Entire home/apt,1.0,1,1,Real Bed,"{""Wireless Internet"",""Air conditioning"",Kitche...",8,3,...,0,1,1,0,1,0,0,0,0,1
1,5.129899,Apartment,Entire home/apt,1.0,3,3,Real Bed,"{""Wireless Internet"",""Air conditioning"",Kitche...",14,7,...,0,1,1,0,1,0,1,1,0,1
2,4.976734,Apartment,Entire home/apt,1.0,1,3,Real Bed,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",18,5,...,1,1,1,0,1,0,0,0,0,1
3,4.744932,Apartment,Entire home/apt,1.0,0,1,Real Bed,"{TV,Internet,""Wireless Internet"",""Air conditio...",12,2,...,0,1,1,0,1,0,0,0,0,1
4,4.442651,Apartment,Private room,1.0,1,1,Real Bed,"{TV,""Wireless Internet"",Heating,""Smoke detecto...",10,2,...,0,1,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55523,5.135798,Apartment,Entire home/apt,1.0,1,1,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",24,2,...,0,1,0,0,1,0,0,0,1,1
55524,4.356709,Apartment,Entire home/apt,1.0,1,1,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",26,2,...,0,1,1,0,1,0,1,1,0,1
55525,4.248495,House,Private room,1.0,1,1,Real Bed,"{TV,Internet,""Wireless Internet"",""Air conditio...",13,2,...,0,1,1,1,1,0,1,1,0,1
55526,5.043425,Apartment,Entire home/apt,2.0,2,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",15,4,...,0,1,1,1,1,0,1,1,0,1
55527,5.220356,Apartment,Entire home/apt,1.0,2,2,Real Bed,"{TV,Internet,""Wireless Internet"",""Air conditio...",31,5,...,0,1,1,0,1,0,1,1,0,1

In [ ]:
df = df.drop('amenities', axis=1)
df

,log_price,property_type,room_type,bathrooms,bedrooms,beds,bed_type,amenities_count,accommodates,cancellation_policy,...,breakfast,internet,kitchen,free parking on premises,air-conditioning or heating,hot tub,washer,dryer,self check-in,tv
0,5.010635,Apartment,Entire home/apt,1.0,1,1,Real Bed,8,3,strict,...,0,1,1,0,1,0,0,0,0,1
1,5.129899,Apartment,Entire home/apt,1.0,3,3,Real Bed,14,7,strict,...,0,1,1,0,1,0,1,1,0,1
2,4.976734,Apartment,Entire home/apt,1.0,1,3,Real Bed,18,5,moderate,...,1,1,1,0,1,0,0,0,0,1
3,4.744932,Apartment,Entire home/apt,1.0,0,1,Real Bed,12,2,moderate,...,0,1,1,0,1,0,0,0,0,1
4,4.442651,Apartment,Private room,1.0,1,1,Real Bed,10,2,strict,...,0,1,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55523,5.135798,Apartment,Entire home/apt,1.0,1,1,Real Bed,24,2,moderate,...,0,1,0,0,1,0,0,0,1,1
55524,4.356709,Apartment,Entire home/apt,1.0,1,1,Real Bed,26,2,strict,...,0,1,1,0,1,0,1,1,0,1
55525,4.248495,House,Private room,1.0,1,1,Real Bed,13,2,moderate,...,0,1,1,1,1,0,1,1,0,1
55526,5.043425,Apartment,Entire home/apt,2.0,2,4,Real Bed,15,4,moderate,...,0,1,1,1,1,0,1,1,0,1
55527,5.220356,Apartment,Entire home/apt,1.0,2,2,Real Bed,31,5,moderate,...,0,1,1,0,1,0,1,1,0,1

In [ ]:
df.to_excel('/content/drive/MyDrive/bda/bda_머신러닝스터디/airbnb_onehot.xlsx', index=False)

In [ ]:
df_onehot = pd.read_excel('/content/drive/MyDrive/bda/bda_머신러닝스터디/airbnb_onehot.xlsx')
df_onehot

,log_price,property_type,room_type,bathrooms,bedrooms,beds,bed_type,amenities_count,accommodates,cancellation_policy,...,breakfast,internet,kitchen,free parking on premises,air-conditioning or heating,hot tub,washer,dryer,self check-in,tv
0,5.010635,Apartment,Entire home/apt,1.0,1,1,Real Bed,8,3,strict,...,0,1,1,0,1,0,0,0,0,1
1,5.129899,Apartment,Entire home/apt,1.0,3,3,Real Bed,14,7,strict,...,0,1,1,0,1,0,1,1,0,1
2,4.976734,Apartment,Entire home/apt,1.0,1,3,Real Bed,18,5,moderate,...,1,1,1,0,1,0,0,0,0,1
3,4.744932,Apartment,Entire home/apt,1.0,0,1,Real Bed,12,2,moderate,...,0,1,1,0,1,0,0,0,0,1
4,4.442651,Apartment,Private room,1.0,1,1,Real Bed,10,2,strict,...,0,1,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55523,5.135798,Apartment,Entire home/apt,1.0,1,1,Real Bed,24,2,moderate,...,0,1,0,0,1,0,0,0,1,1
55524,4.356709,Apartment,Entire home/apt,1.0,1,1,Real Bed,26,2,strict,...,0,1,1,0,1,0,1,1,0,1
55525,4.248495,House,Private room,1.0,1,1,Real Bed,13,2,moderate,...,0,1,1,1,1,0,1,1,0,1
55526,5.043425,Apartment,Entire home/apt,2.0,2,4,Real Bed,15,4,moderate,...,0,1,1,1,1,0,1,1,0,1
55527,5.220356,Apartment,Entire home/apt,1.0,2,2,Real Bed,31,5,moderate,...,0,1,1,0,1,0,1,1,0,1

In [ ]:
df_onehot['property_type'].describe()

count         55528
unique            9
top       Apartment
freq          37294
Name: property_type, dtype: object

In [ ]:
df_onehot.isnull().sum()

log_price                      0
property_type                  0
room_type                      0
bathrooms                      0
bedrooms                       0
beds                           0
bed_type                       0
amenities_count                0
accommodates                   0
cancellation_policy            0
cleaning_fee                   0
city                           0
latitude                       0
longitude                      0
number_of_reviews              0
review_scores_rating           0
pool                           0
breakfast                      0
internet                       0
kitchen                        0
free parking on premises       0
air-conditioning or heating    0
hot tub                        0
washer                         0
dryer                          0
self check-in                  0
tv                             0
dtype: int64